baseurl: "/"
title: "Introduction to Spatio-Temporal Models"
author: "Colin Rundel"
copyright: "&copy; 2022. All rights reserved."
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir: "docs"

menu:
  main:
  - name: Syllabus
    pre: <i class='fa fa-file-text-o fa-fw'></i>
    weight: 2
    identifier: syllabus
    url: "#syllabus"
  - name: Sakai
    pre: <i class="fas fa-chalkboard-teacher"></i>
    weight: 3
    url: https://sakai.duke.edu/portal/site/ce7276bc-e677-46ce-a1e6-9c3f98d6d465
  - name: Github
    pre: <i class='fa fa-github fa-fw'></i>
    weight: 6
    url: https://github.com/sta344-fa22
  - name: RStudio
    pre: <i class='fab fa-r-project fa-fw'></i>
    weight: 7
    url: http://rstudio.stat.duke.edu:8787

params:
  subtitle: "(Fall 2022)"
  course: "Sta 344"
  highlightjs: androidstudio
  highlightjs_extra_languages:
    - yaml
  dateFormat: '02 Jan 2006, 15:04'
  sections:
    - schedule
    - syllabus
    - textbooks
    - about
  contact:
    - name: Dr. Colin Rundel
      office: 204 Old Chemistry
      email: colin.rundel@duke.edu
      hours: TBD
  assignments:
    - name: Homework
      value: 40%
    - name: Midterms
      value: 40%
    - name: Project
      value: 20%
